version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - UPLOAD_DIR=./uploads
      - MODEL_PATH=./model_files/brain_tumor_model.pth
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/brain_tumor_detection
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - ./backend/model_files:/app/model_files
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=brain_tumor_detection
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 